### PR TITLE
2014 chaudhary

### PR DESCRIPTION
**Pull request by grzanka**
@fkalholm 
Last one to clean

### CODE REVIEW

**Comment by fkalholm** [comment]
should be cleaned up now, and synced with mater branch

**Comment by grzanka** [comment]
@fkalholm what are the changes in 2020_Furusawa directory in this PR ?

**Comment by fkalholm** [comment]
@grzanka Before, I used a slightly different method to extract the range shifter thickness in the furusawa-paper, so I kept some seperate src-folders there. But when thinking about it now, it makes better sense to have it also in the same structure as the rest. So I have now organized it in the same way as the rest.

**Comment by grzanka** [comment]
@fkalholm what is the status of this PR ?

**Comment by fkalholm** [comment]
thanks for asking, must have forgot to actually merge them before

**Pull request merged**
