### PR TITLE
submission files

### LINKED ISSUE #10: Simulate Guan_2015
@grzanka , could you help me simulate the protons for the Guan data? You can generate the files by running "mcscripter config_H.cfg" in the "/PubSim/2015_Guan/sim-files"-folder.
I dont know how many particles you used last time, but a similar, or even slightly smaller amount would probably be ok.

### PR DESCRIPTION
**Pull request by grzanka**
Fixes #10

### CODE REVIEW

**Comment by grzanka** [comment]
@fkalholm can you cross-check how to collect the data with recent code ?

README https://github.com/nbassler/PubSim/blob/feature/10_guan_2015/2015_Guan/README.md mentions `collect_data.py under src/,` - where to find it ?

**Comment by fkalholm** [comment]
This should be the collect_data_mult.py (can just change name of the file)

**Comment by grzanka** [comment]
@fkalholm can you take a look on the complete data set ?
I've created new collect script (https://github.com/nbassler/PubSim/pull/11/files#diff-1640835f1fee7c36287341f690665033cfbe2e6a0ec859a411d2269a38f5c12a) which reads binary files and saves a text file (with .dat extension) in each folder:
[data.zip](https://github.com/nbassler/PubSim/files/6511226/data.zip)

Probably the further processing needs to be adapted

**Comment by grzanka** [comment]
Hi @fkalholm ,

I've added new script which is merging data from different directories, see 
[summary.zip](https://github.com/nbassler/PubSim/files/6515584/summary.zip)

Example output of the script is here:
https://github.com/nbassler/PubSim/pull/11/files#diff-0a621449cfd6e9399f9b7c9f5db5511aeec16b1df9bdbb679298e38ec42f33fe

You can quickly read it with pandas:

```
import pandas as pd
df = pd.read_csv('summary.csv', index_col=["stat_moment", "ion", "thickness"])
```

**Comment by grzanka** [comment]
TODO for @grzanka : add a file with run summary (SH12A version and other metadata)

**Pull request merged**
